In [2]:
import pandas as pd
base = pd.read_csv('original.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [3]:
x=base.iloc[:, 5:6].values
y=base.iloc[:, 2:3 ].values
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x = scaler_x.fit_transform(x)
scaler_y = StandardScaler()
y = scaler_y.fit_transform(y)
print(base.columns)

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')


/Users/kewinkuster/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/Users/kewinkuster/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [6]:
import tensorflow as tf
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']
print(colunas_usadas)
base=pd.read_csv('original.csv', usecols = colunas_usadas)
base.head()

['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long']


price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
x = base.drop('price', axis =1 )
y = base.price

In [11]:
x.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [12]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [13]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [21]:
import tensorflow as tf

In [22]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [23]:
print(colunas[0])

NumericColumn(key='bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [24]:
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x,y,test_size=0.3)

In [28]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(
    x = x_treinamento,y = y_treinamento,batch_size=32, 
    num_epochs=None, shuffle=True)

In [29]:
teste = tf.estimator.inputs.pandas_input_fn(
    x = x_teste,y = y_teste,batch_size=32, 
    num_epochs=10000, shuffle=False)

In [30]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

W0410 14:57:51.637042 4523562432 estimator.py:1811] Using temporary folder as model directory: /var/folders/mf/9h2x7zx15t9986ylpx3t_29c0000gn/T/tmp807nqzdj


In [31]:
regressor.train(input_fn=funcao_treinamento,steps=10000)

W0410 14:58:24.580974 4523562432 deprecation.py:323] From /Users/kewinkuster/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
W0410 14:58:24.612108 4523562432 deprecation.py:323] From /Users/kewinkuster/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/inputs/queues/feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0410 14:58:24.614739 4523562432 deprecation.py:323] From /Users/kewinkuster/anaconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/input

In [33]:
metricas_treinamento=regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

W0410 14:59:44.225741 4523562432 deprecation.py:323] From /Users/kewinkuster/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


In [35]:
metricas_teste=regressor.evaluate(input_fn=teste, steps=10000)

In [36]:
metricas_treinamento

{'average_loss': 0.0007242137,
 'label/mean': 0.06120844,
 'loss': 0.02317484,
 'prediction/mean': 0.058105834,
 'global_step': 10000}

In [37]:
metricas_teste

{'average_loss': 0.0006783271,
 'label/mean': 0.060478814,
 'loss': 0.021706467,
 'prediction/mean': 0.05747548,
 'global_step': 10000}

In [38]:
funcao_previsao=tf.estimator.inputs.pandas_input_fn(x=x_teste
        ,shuffle = False)

In [39]:
previsores=regressor.predict(input_fn=funcao_previsao)

In [41]:
list(previsores)

[{'predictions': array([0.10466339], dtype=float32)},
 {'predictions': array([0.01639085], dtype=float32)},
 {'predictions': array([0.06172956], dtype=float32)},
 {'predictions': array([0.08701021], dtype=float32)},
 {'predictions': array([0.12918955], dtype=float32)},
 {'predictions': array([0.18126985], dtype=float32)},
 {'predictions': array([0.04532877], dtype=float32)},
 {'predictions': array([0.02617412], dtype=float32)},
 {'predictions': array([0.03812409], dtype=float32)},
 {'predictions': array([0.05443648], dtype=float32)},
 {'predictions': array([0.02858999], dtype=float32)},
 {'predictions': array([0.1815426], dtype=float32)},
 {'predictions': array([0.03088684], dtype=float32)},
 {'predictions': array([0.16677889], dtype=float32)},
 {'predictions': array([0.02498843], dtype=float32)},
 {'predictions': array([0.06389988], dtype=float32)},
 {'predictions': array([0.02809598], dtype=float32)},
 {'predictions': array([0.1569815], dtype=float32)},
 {'predictions': array([0.0655

In [44]:
valores_previsoes=[]
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

In [45]:
valores_previsoes

[array([0.10466339], dtype=float32),
 array([0.01639085], dtype=float32),
 array([0.06172956], dtype=float32),
 array([0.08701021], dtype=float32),
 array([0.12918955], dtype=float32),
 array([0.18126985], dtype=float32),
 array([0.04532877], dtype=float32),
 array([0.02617412], dtype=float32),
 array([0.03812409], dtype=float32),
 array([0.05443648], dtype=float32),
 array([0.02858999], dtype=float32),
 array([0.1815426], dtype=float32),
 array([0.03088684], dtype=float32),
 array([0.16677889], dtype=float32),
 array([0.02498843], dtype=float32),
 array([0.06389988], dtype=float32),
 array([0.02809598], dtype=float32),
 array([0.1569815], dtype=float32),
 array([0.06557063], dtype=float32),
 array([0.10318815], dtype=float32),
 array([0.09061121], dtype=float32),
 array([0.06354266], dtype=float32),
 array([0.05337164], dtype=float32),
 array([0.03089594], dtype=float32),
 array([0.02976517], dtype=float32),
 array([0.04142164], dtype=float32),
 array([0.03686012], dtype=float32),
 ar

In [46]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [47]:
valores_previsoes

array([[0.10466339],
       [0.01639085],
       [0.06172956],
       ...,
       [0.03390373],
       [0.06065763],
       [0.0816813 ]], dtype=float32)

In [50]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)

In [51]:
y_teste

9812     0.075410
16814    0.009836
15873    0.100328
6944     0.055607
18402    0.098361
722      0.197115
12069    0.043213
6363     0.024911
11039    0.049049
18820    0.052452
1494     0.045902
9603     0.141928
903      0.016393
9553     0.225574
8421     0.032125
17263    0.070623
8700     0.033443
2023     0.184262
19093    0.049180
6970     0.086754
8869     0.100787
18531    0.041311
15559    0.032131
12808    0.046820
18797    0.022289
11316    0.021639
2252     0.034754
12458    0.075410
17668    0.051148
13040    0.092157
           ...   
15270    0.050098
9110     0.128197
16361    0.017311
13125    0.023856
4924     0.099344
16979    0.044590
9545     0.015082
4719     0.045246
11702    0.022951
18729    0.030689
14048    0.074085
12964    0.049902
13218    0.024918
8010     0.024393
20666    0.110053
13165    0.062033
21513    0.056393
475      0.058361
4382     0.049180
804      0.040682
21141    0.236721
20009    0.061967
15244    0.077705
18695    0.091148
894      0

In [52]:
y_teste2=y_teste.values.reshape(-1,1)


In [55]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes )

In [56]:
mae

514043.6438349442